networks:
  npm_service:
  repo_rangler_proxy:
    name: repo_rangler_proxy
    external: true

services:
  npm_service_nginx:
    container_name: reporangler_npm_service_nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    networks:
      - repo_rangler_proxy
      - npm_service
    volumes:
      - ./public:/www/public:ro
    environment:
      - VIRTUAL_HOST=npm.reporangler.localhost
    depends_on:
      - npm_service_phpfpm

  npm_service_phpfpm:
    container_name: reporangler_npm_service_phpfpm
    build:
      context: .
      dockerfile: docker/phpfpm/Dockerfile
    networks:
      - npm_service
    volumes:
      - .:/www
      - ../lib-reporangler:/lib-reporangler:ro
    env_file:
      - .env
